//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddStrip {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddStripForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddStripForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddStrip.AddStripForm", typeof(AddStripForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point menuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter an Operand in the calculation box..
        /// </summary>
        public static string operandAbsentWarning {
            get {
                return ResourceManager.GetString("operandAbsentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Operands should have the form [+ or -]&lt;numbers&gt;. \r\nE.G: +10, -20, 5.
        /// </summary>
        public static string operandDescriptionWarning {
            get {
                return ResourceManager.GetString("operandDescriptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234567890.
        /// </summary>
        public static string operandDigits {
            get {
                return ResourceManager.GetString("operandDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operand could not be converted to a valid number.
        /// </summary>
        public static string operandInvalidFormatWarning {
            get {
                return ResourceManager.GetString("operandInvalidFormatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no calculations to total or subtotal..
        /// </summary>
        public static string operandInvalidTotalWarning {
            get {
                return ResourceManager.GetString("operandInvalidTotalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +-.
        /// </summary>
        public static string operandSigns {
            get {
                return ResourceManager.GetString("operandSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Termination symbol. Must be one of: +-*/#= \r\nE.G: +10+, +10-, +10*, +10/, +10#, +10=.
        /// </summary>
        public static string operatorInvalidTerminationWarning {
            get {
                return ResourceManager.GetString("operatorInvalidTerminationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +-*/#=.
        /// </summary>
        public static string operatorTerminators {
            get {
                return ResourceManager.GetString("operatorTerminators", resourceCulture);
            }
        }
    }
}
